services:
  api1: &api
    build: .
    ports:
      - 3001:3000
    volumes:
      - ./:/opt
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '60MB' 
    
  api2:
    <<: *api
    ports:
      - 3002:3000

  worker_light:
    build: .
    depends_on:
      - redis
    environment:
      - APP_ENV=docker
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    command: perl scripts/worker_light.pl
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '40MB'

  worker_heavy:
    build: .
    depends_on:
      - redis
    environment:
      - APP_ENV=docker
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    command: script/worker_heavy
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '100MB'

  nginx:
    image: nginx
    depends_on:
      - api1
      - api2
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  redis:
    image: redis:7.2-alpine
    command: redis-server --save "" --appendonly no --maxclients 20000
    hostname: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true